version: "3"

volumes:
  pgdata:

services:
  pgsql:
    image: postgres:11.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  svc:
    image: whowon
    volumes:
      # edit the app on the fly
      - ./src:/app/src
    ports:
      - "5000:5000"
    depends_on:
      - pgsql
    tty: true