version: "3"

volumes:
  pgdata:

services:
  # pgsql:
  #   image: postgres:11.7
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=secret
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  svc:
    build: .
    # image: battles
    volumes: ["./src:/app/src",
              ".env:/app/.env"]
    ports: ["5000:5000"]
    # depends_on:
    #   - pgsql
    tty: true
    command: bash

  # test:
  #   image: python:3.9-slim
  #   volumes: ["./src:/app/src",
  #             ".env:/app/.env"]
  #   ports: ["5000:5000"]
  #   # depends_on:
  #   #   - pgsql
  #   tty: true
  #   command: bash