"""Initial migration.

Revision ID: 55716888cf2f
Revises: 
Create Date: 2022-03-03 18:18:08.128133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55716888cf2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battleName', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('answer', sa.Enum('a', 'b', name='result'), nullable=False),
    sa.Column('belligerentA', sa.String(length=100), nullable=False),
    sa.Column('belligerentB', sa.String(length=100), nullable=False),
    sa.Column('leaderAName', sa.String(length=100), nullable=False),
    sa.Column('leaderBName', sa.String(length=100), nullable=False),
    sa.Column('leaderAImageLink', sa.String(length=100), nullable=False),
    sa.Column('leaderBImageLink', sa.String(length=100), nullable=False),
    sa.Column('wikipediaBlurb', sa.String(length=450), nullable=True),
    sa.Column('wikipediaLink', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_read_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('battleName')
    )
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_page_hits', sa.Integer(), nullable=True),
    sa.Column('num_battles', sa.Integer(), nullable=True),
    sa.Column('num_success', sa.Integer(), nullable=True),
    sa.Column('num_failure', sa.Integer(), nullable=True),
    sa.Column('last_used_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('battles')
    # ### end Alembic commands ###
